<?php

use Illuminate\Database\Seeder;

class PersonalInfosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        // テーブルのクリア
        DB::table('personal_infos')->truncate();

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        // 初期データ用意（列名をキーとする連想配列）
        $infos=[
            ['id'=>1,
            'clint_name'=>'石垣浩二',
            'birth_date'=> '1963-3-25',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>2,
            'clint_name'=>'石畠誠二',
            'birth_date'=> '1986-1-27',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>3,
            'clint_name'=>'井上勝美',
            'birth_date'=> '1985-1-7',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>4,
            'clint_name'=>'上野仁美',
            'birth_date'=> '1969-5-4',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>5,
            'clint_name'=>'岡洋平',
            'birth_date'=> '1984-5-10',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>6,
            'clint_name'=>'岡崎美年子',
            'birth_date'=> '1979-5-11',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>7,
            'clint_name'=>'川上務',
            'birth_date'=> '1978-3-31',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>8,
            'clint_name'=>'黒飛和倫',
            'birth_date'=> '1984-11-1',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>9,
            'clint_name'=>'小林紀子',
            'birth_date'=> '1976-7-5',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>10,
            'clint_name'=>'才間利江',
            'birth_date'=> '1975-5-13',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>11,
            'clint_name'=>'才間雄二',
            'birth_date'=> '1973-9-29',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>12,
            'clint_name'=>'豊田真也',
            'birth_date'=> '1964-11-26',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>13,
            'clint_name'=>'東昇',
            'birth_date'=> '1974-10-14',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>14,
            'clint_name'=>'平山心太',
            'birth_date'=> '1992-8-19',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>15,
            'clint_name'=>'藤井芳明',
            'birth_date'=> '1975-12-1',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>16,
            'clint_name'=>'藤尾忠宏',
            'birth_date'=> '1967-12-28',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>17,
            'clint_name'=>'藤原圭司',
            'birth_date'=> '1971-9-7',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>18,
            'clint_name'=>'的場一生',
            'birth_date'=> '1977-7-30',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>19,
            'clint_name'=>'溝川有希',
            'birth_date'=> '1976-3-6',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>20,
            'clint_name'=>'宮原佑基',
            'birth_date'=> '1987-6-13',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>21,
            'clint_name'=>'宮本幸子',
            'birth_date'=> '1987-9-27',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>22,
            'clint_name'=>'村上義治',
            'birth_date'=> '1969-5-21',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>23,
            'clint_name'=>'元廣紀子',
            'birth_date'=> '1966-2-11',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>24,
            'clint_name'=>'矢野浩二',
            'birth_date'=> '1972-2-12',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>25,
            'clint_name'=>'横山久子',
            'birth_date'=> '1968-6-3',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>26,
            'clint_name'=>'岡田真智子',
            'birth_date'=> '1959-12-28',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>27,
            'clint_name'=>'宮地未来',
            'birth_date'=> '2000-2-10',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>28,
            'clint_name'=>'久田清美',
            'birth_date'=> '1959-9-13',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>29,
            'clint_name'=>'小林大一郎',
            'birth_date'=> '1995-11-11',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>30,
            'clint_name'=>'佐木輝昭',
            'birth_date'=> '1957-12-2',
            'sex'=> 0,
            'height'=> 0],
            ['id'=>31,
            'clint_name'=>'江原萌香',
            'birth_date'=> '2000-4-3',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>32,
            'clint_name'=>'藤本真実',
            'birth_date'=> '1989-9-28',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>33,
            'clint_name'=>'工藤南名',
            'birth_date'=> '2002-6-15',
            'sex'=> 1,
            'height'=> 0],
            ['id'=>34,
            'clint_name'=>'小林千鶴',
            'birth_date'=> '2002-6-25',
            'sex'=> 1,
            'height'=> 0],
            ];

            foreach($infos as $info) {
                \App\Models\PersonalInfo::create($info);

            }
        }
}
